### PR TITLE
build(jest): run all tests

### PR DESCRIPTION
**Pull request by bpinto**
Depends on #2

### CODE REVIEW

**Review by niklaas — COMMENTED** [review]
How would you like to run it? Isn't an `npm i` missing somewhere? 🤔 

```
~/git/red-guava/cliniko-jscodeshifting git:[run-all-tests]
docker-compose run app

[+] Building 1.0s (6/6) FINISHED                                                                                         docker:orbstack
 => [app internal] load build definition from Dockerfile                                                                            0.0s
 => => transferring dockerfile: 80B                                                                                                 0.0s
 => [app internal] load metadata for docker.io/library/node:20.14.0-alpine                                                          0.9s
 => [app internal] load .dockerignore                                                                                               0.0s
 => => transferring context: 2B                                                                                                     0.0s
 => [app 1/2] FROM docker.io/library/node:20.14.0-alpine@sha256:66c7d989b6dabba6b4305b88f40912679aebd9f387a5b16ffa76dfb9ae90b060    0.0s
 => CACHED [app 2/2] WORKDIR /src/app                                                                                               0.0s
 => [app] exporting to image                                                                                                        0.0s
 => => exporting layers                                                                                                             0.0s
 => => writing image sha256:d7c557ad88d65e4540f8f7ac272e50cc3982d44049ee81d9b3018e72ceb356b9                                        0.0s
 => => naming to docker.io/library/cliniko-jscodeshifting-app                                                                       0.0s

> test
> jest --bail

sh: jest: not found
```

**Comment by bpinto** [comment]
As if you were running on your computer, you need to run `npm install` before running `npm run test`. This is to avoid having the packages installed inside of the docker image which would then cause us to have to constantly rebuild the entire image which will take considerably more time than updating the packages you have installed in a docker volume.

**Comment by niklaas** [comment]
> As if you were running on your computer, you need to run `npm install` before running `npm run test`.

Ah, thanks, that makes sense! I don't have a lot of experience with docker, so don't know the common patterns that are used. 👍🏼

**Review by niklaas — APPROVED** [review]

**Comment by bpinto** [comment]
> Ah, thanks, that makes sense! I don't have a lot of experience with docker, so don't know the common patterns that are used. 👍🏼

It was a good question, and that would be doable, but it slows down development a lot. We do that (npm install) on production images only.

**Pull request merged**
